version: "3"
services:
  redis:
    image: redis:latest
    command: redis-server
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
  cardinal:
    build: ./cardinal
    depends_on:
      - redis
    expose:
      - "3333"
    ports:
      - "3333:3333"
    environment:
      - CARDINAL_PORT=3333
      - REDIS_ADDR=redis:6379
      - REDIS_MODE=normal
volumes:
  data:
